services:
  db:
    build: ./docker/db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
  springboot:
    build:
      context: .
      dockerfile: docker/springboot/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
