name: Build and Push Docker Image

on:
  push:
    branches:
      - 'docker-action'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/pienskoi/streaming_platform:latest
          file: docker/jar/Dockerfile
          cache-from: type=registry,ref=ghcr.io/pienskoi/streaming_platform:latest
          cache-to: type=inline
          
